### ISSUE TITLE
Leaflet issue after recyle and marker position on 7.7.8

### ISSUE THREAD

**Issue by simoneldevig** [Joniff/Terratype#13]
Hello,

I've just installed this package on a Umbraco 7.7.8 where I expirience the following issues:

1. When using this package with Leaflet as provider i get an issue everytime i recylcle the app pool, where the package says that there isn't any Map Provider added to the Terratype datatype even though I just added it. The only that makes it work again is a rebuild. 

2. I'm using the package with Nested Content which works great and I also get the right data out in the Razor template but it positions all the markers on the same map(default) position even though the value is different in both Backoffice and the value shown on the position marker.

I hope that you are able to help with these issues :-)

Best Regards

**Comment by Joniff** [comment]
Hi,

I'm sorry about issue 1, this is something I changed in the last version to improve it, and it seems to have edge case issues. There will be a fix for this very soon.

In regard to issue 2, which I would like to fix in the same release. Can I ask ?

You have multiple leaflet maps within a nested content property. Each of these maps is different, but when they are rendered you say the icons are merged, just to check can you tell if its the map icons that are wrong or the map clustering icons that are wrong. Just so that I can fully understand, could you 
A) Post a screenshot of the map, as shown in your browser.
B) Could you post a snippet of your razor code, so I can see what Terratype options etc you are using. And to sanity check your nested content code.
C) I suspect I won't need it yet, but maybe ready yourself to post the json that is being stored for each Terratype property. If you don't know how to do this, don't worry, I'll explain how to do it if I do require it.

Cheers

**Comment by simoneldevig** [comment]
Thanks for the reply @Joniff.

Great about issue 1!

Regarding issue 2 I was able to solve this by reinstalling the package. Don't know what caused the issue be a reinstall fixed it :-)

Since you will fix issue 1 I will go ahead an close this issue.
